name: CI workflow

on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test with pytest
      run: |
        pytest